SET LINESIZE 500
SET PAGESIZE 30000
spool cpfatuprod.txt
SELECT ALL LPAD(A.NUM_NOTA_FISCAL,6,0)||'-'||SUBSTR(A.SERIE_NOTA_FISC,1,3) Nota, 
           A.DATA_EMISSAO_NF Emissao,
           B.DATA_PROD_TECEL Producao,
           A.NIVEL_ESTRUTURA||'.'||
           A.GRUPO_ESTRUTURA||'.'||
           A.SUBGRU_ESTRUTURA||'.'||
           A.ITEM_ESTRUTURA||' - '||
           A.DESCR_REFERENCIA Produto, 
           B.CODIGO_ROLO CDRolo, 
           B.QTDE_QUILOS_ACAB Quant, 
           B.QTDE_QUILOS_ACAB*A.VALOR_UNITARIO VL_ITEM, 
           SUBSTR(FU_MES_NUM(A.DATA_EMISSAO_NF),1,9) MESFATU, 
           SUBSTR(FU_MES_NUM(B.DATA_PROD_TECEL),1,9) MESPROD
FROM VW_FATURAMENTO A, PCPT_020 B
WHERE (A.DATA_EMISSAO_NF BETWEEN '01-JUL-06' AND '31-JUL-06'
  --AND  FU_MES_NUM(A.DATA_EMISSAO_NF)<> FU_MES_NUM(B.DATA_PROD_TECEL)
  AND  A.NIVEL_ESTRUTURA=2)
  AND (A.TIPO_MOEDA=1 OR A.TIPO_MOEDA is null)
  AND ((A.NUM_NOTA_FISCAL=B.NOTA_FISCAL)
  AND  (A.SERIE_NOTA_FISC=B.SERIE_FISCAL_SAI)
  AND  (A.NIVEL_ESTRUTURA=B.PANOACAB_NIVEL99)
  AND  (A.GRUPO_ESTRUTURA=B.PANOACAB_GRUPO)
  AND  (A.SUBGRU_ESTRUTURA=B.PANOACAB_SUBGRUPO)
  AND  (A.ITEM_ESTRUTURA=B.PANOACAB_ITEM))
ORDER BY A.NUM_NOTA_FISCAL ASC, 
         A.SERIE_NOTA_FISC ASC, 
         A.DATA_EMISSAO_NF ASC;
spool off
exit